
/*
 * 
 */

package client.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Nov 11 19:03:34 CET 2010
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "CustomerService", 
                  wsdlLocation = "http://localhost:9000/customerservice?wsdl",
                  targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/customer")
public class CustomerService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://infosys.tuwien.ac.at/aic10/ass1/dto/customer", "CustomerService");
    public final static QName CustomerManagementPT = new QName("http://infosys.tuwien.ac.at/aic10/ass1/dto/customer", "CustomerManagementPT");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9000/customermanagementservice?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9000/customerservice?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CustomerWrapperService
     */
    @WebEndpoint(name = "CustomerManagementPT")
    public CustomerWrapperService getCustomerManagementPT() {
        return super.getPort(CustomerManagementPT, CustomerWrapperService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerWrapperService
     */
    @WebEndpoint(name = "CustomerManagementPT")
    public CustomerWrapperService getCustomerManagementPT(WebServiceFeature... features) {
        return super.getPort(CustomerManagementPT, CustomerWrapperService.class, features);
    }

}
