package client.gui.cfg;

public enum GameCellType {
	PACMAN_GREEN,PACMAN_RED,PACMAN_BLUE,
	WALL,WALL_GREEN,WALL_BLUE,WALL_RED,
	WALL_PACMAN_GREEN,WALL_PACMAN_BLUE,WALL_PACMAN_RED,
	FRUIT1,FRUIT2,FRUIT3,
	NONE
}
