
package dst3.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SearchBeanService", targetNamespace = "http://ejb.dst3/", wsdlLocation = "http://localhost:8080/dst3/SearchBeanService?wsdl")
public class SearchBeanService
    extends Service
{

    private final static URL SEARCHBEANSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/dst3/SearchBeanService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SEARCHBEANSERVICE_WSDL_LOCATION = url;
    }

    public SearchBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchBeanService() {
        super(SEARCHBEANSERVICE_WSDL_LOCATION, new QName("http://ejb.dst3/", "SearchBeanService"));
    }

    /**
     * 
     * @return
     *     returns SearchBean
     */
    @WebEndpoint(name = "SearchBeanPort")
    public SearchBean getSearchBeanPort() {
        return (SearchBean)super.getPort(new QName("http://ejb.dst3/", "SearchBeanPort"), SearchBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchBean
     */
    @WebEndpoint(name = "SearchBeanPort")
    public SearchBean getSearchBeanPort(WebServiceFeature... features) {
        return (SearchBean)super.getPort(new QName("http://ejb.dst3/", "SearchBeanPort"), SearchBean.class, features);
    }

}
