
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package client.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Nov 11 19:03:34 CET 2010
 * Generated source version: 2.2.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "CustomerService",
                      portName = "CustomerManagementPT",
                      targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping",
                      wsdlLocation = "http://localhost:9000/customerservice?wsdl",
                      endpointInterface = "client.services.CustomerWrapperService")
                      
public class CustomerWrapperServiceImpl implements CustomerWrapperService {

    private static final Logger LOG = Logger.getLogger(CustomerWrapperServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see client.services.CustomerWrapperService#getCustomer(java.lang.String  id )*
     */
    public client.services.Customer getCustomer(java.lang.String id) { 
        LOG.info("Executing operation getCustomer");
        System.out.println(id);
        try {
            client.services.Customer _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see client.services.CustomerWrapperService#updateCustomer(client.services.Customer  customer )*
     */
    public void updateCustomer(client.services.Customer customer) { 
        LOG.info("Executing operation updateCustomer");
        System.out.println(customer);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see client.services.CustomerWrapperService#updateAccount(client.services.Customer  customer ,)java.math.BigDecimal  valueChanged )*
     */
    public void updateAccount(client.services.Customer customer,java.math.BigDecimal valueChanged) { 
        LOG.info("Executing operation updateAccount");
        System.out.println(customer);
        System.out.println(valueChanged);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see client.services.CustomerWrapperService#deleteCustomer(java.lang.String  id )*
     */
    public void deleteCustomer(java.lang.String id) { 
        LOG.info("Executing operation deleteCustomer");
        System.out.println(id);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see client.services.CustomerWrapperService#addCustomer(client.services.Customer  customer )*
     */
    public void addCustomer(client.services.Customer customer) { 
        LOG.info("Executing operation addCustomer");
        System.out.println(customer);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see client.services.CustomerWrapperService#notify(java.lang.String  customer ,)java.lang.String  message )*
     */
    public void notify(java.lang.String customer,java.lang.String message) { 
        LOG.info("Executing operation notify");
        System.out.println(customer);
        System.out.println(message);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
