
/*
 * 
 */

package client.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Nov 11 17:09:59 CET 2010
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "RegistryService", 
                  wsdlLocation = "http://localhost:9000/registryservice?wsdl",
                  targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping") 
public class RegistryService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", "RegistryService");
    public final static QName RegistryPT = new QName("http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", "RegistryPT");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9000/registryservice?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9000/registryservice?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RegistryService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistryService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns RegistryService
     */
    @WebEndpoint(name = "RegistryPT")
    public RegistryService getRegistryPT() {
        return super.getPort(RegistryPT, RegistryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistryService
     */
    @WebEndpoint(name = "RegistryPT")
    public RegistryService getRegistryPT(WebServiceFeature... features) {
        return super.getPort(RegistryPT, RegistryService.class, features);
    }

}
