
package client.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Nov 11 17:09:49 CET 2010
 * Generated source version: 2.2.3
 * 
 */

@WebFault(name = "UnknownAddressFault", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping")
public class UnknownAddressFault_Exception extends Exception {
    public static final long serialVersionUID = 20101111170949L;
    
    private client.services.UnknownAddressFault unknownAddressFault;

    public UnknownAddressFault_Exception() {
        super();
    }
    
    public UnknownAddressFault_Exception(String message) {
        super(message);
    }
    
    public UnknownAddressFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownAddressFault_Exception(String message, client.services.UnknownAddressFault unknownAddressFault) {
        super(message);
        this.unknownAddressFault = unknownAddressFault;
    }

    public UnknownAddressFault_Exception(String message, client.services.UnknownAddressFault unknownAddressFault, Throwable cause) {
        super(message, cause);
        this.unknownAddressFault = unknownAddressFault;
    }

    public client.services.UnknownAddressFault getFaultInfo() {
        return this.unknownAddressFault;
    }
}
