package client.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Nov 11 19:03:34 CET 2010
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", name = "CustomerWrapperService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerWrapperService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCustomer", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.GetCustomer")
    @ResponseWrapper(localName = "getCustomerResponse", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.GetCustomerResponse")
    @WebMethod
    public client.services.Customer getCustomer(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.UpdateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.UpdateCustomerResponse")
    @WebMethod
    public void updateCustomer(
        @WebParam(name = "customer", targetNamespace = "")
        client.services.Customer customer
    );

    @RequestWrapper(localName = "update_account", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.UpdateAccount")
    @ResponseWrapper(localName = "update_accountResponse", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.UpdateAccountResponse")
    @WebMethod(operationName = "update_account")
    public void updateAccount(
        @WebParam(name = "customer", targetNamespace = "")
        client.services.Customer customer,
        @WebParam(name = "valueChanged", targetNamespace = "")
        java.math.BigDecimal valueChanged
    );

    @RequestWrapper(localName = "deleteCustomer", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.DeleteCustomer")
    @ResponseWrapper(localName = "deleteCustomerResponse", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.DeleteCustomerResponse")
    @WebMethod
    public void deleteCustomer(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @RequestWrapper(localName = "addCustomer", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.AddCustomer")
    @ResponseWrapper(localName = "addCustomerResponse", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.AddCustomerResponse")
    @WebMethod
    public void addCustomer(
        @WebParam(name = "customer", targetNamespace = "")
        client.services.Customer customer
    );

    @RequestWrapper(localName = "notify", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.Notify")
    @ResponseWrapper(localName = "notifyResponse", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.NotifyResponse")
    @WebMethod
    public void notify(
        @WebParam(name = "customer", targetNamespace = "")
        java.lang.String customer,
        @WebParam(name = "message", targetNamespace = "")
        java.lang.String message
    );
}
