
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package client.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Nov 11 17:09:59 CET 2010
 * Generated source version: 2.2.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "RegistryService",
                      portName = "RegistryPT",
                      targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping",
                      wsdlLocation = "http://localhost:9000/registryservice?wsdl",
                      endpointInterface = "client.services.RegistryService")
                      
public class RegistryServiceImpl implements RegistryService {

    private static final Logger LOG = Logger.getLogger(RegistryServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see client.services.RegistryService#getProductSupplier(java.lang.String  product )*
     */
    public client.services.EndpointReferenceType getProductSupplier(java.lang.String product) throws UnknownProductFault_Exception    { 
        LOG.info("Executing operation getProductSupplier");
        System.out.println(product);
        try {
            client.services.EndpointReferenceType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UnknownProductFault_Exception("UnknownProductFault...");
    }

}
