package client.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Nov 11 17:09:49 CET 2010
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", name = "ShippingService")
@XmlSeeAlso({ObjectFactory.class})
public interface ShippingService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ship_items", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.ShipItems")
    @ResponseWrapper(localName = "ship_itemsResponse", targetNamespace = "http://infosys.tuwien.ac.at/aic10/ass1/dto/shipping", className = "client.services.ShipItemsResponse")
    @WebMethod(operationName = "ship_items")
    public java.lang.String shipItems(
        @WebParam(name = "items", targetNamespace = "")
        java.util.List<client.services.Item> items,
        @WebParam(name = "address", targetNamespace = "")
        client.services.Addresses address
    ) throws UnknownAddressFault_Exception, UnknownProductFault_Exception;
}
