
package client.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Nov 11 17:10:22 CET 2010
 * Generated source version: 2.2.3
 * 
 */

@WebFault(name = "UnknownProductFault", targetNamespace = "http://interfaces.services/")
public class UnknownProductFault_Exception extends Exception {
    public static final long serialVersionUID = 20101111171022L;
    
    private client.services.UnknownProductFault unknownProductFault;

    public UnknownProductFault_Exception() {
        super();
    }
    
    public UnknownProductFault_Exception(String message) {
        super(message);
    }
    
    public UnknownProductFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownProductFault_Exception(String message, client.services.UnknownProductFault unknownProductFault) {
        super(message);
        this.unknownProductFault = unknownProductFault;
    }

    public UnknownProductFault_Exception(String message, client.services.UnknownProductFault unknownProductFault, Throwable cause) {
        super(message, cause);
        this.unknownProductFault = unknownProductFault;
    }

    public client.services.UnknownProductFault getFaultInfo() {
        return this.unknownProductFault;
    }
}
